spring.application.name=SerratecFlix

application.properties
#Porta do servidor
server.port=8080

#Conexao com banco
spring.datasource.url=jdbc:postgresql://localhost:5432/serratecflix
spring.datasource.username=postgres
spring.datasource.password=

#DDL - como o hibernate trata a estrutura do banco
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true

#SQL no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Dialeto
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Script Inicial do Banco de Dados
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql
spring.jpa.defer-datasource-initialization=true

#Formatação do json
spring.jackson.serialization.indent-output=true

gemini.api.key=${GEMINI_API_KEY}
